name: CI - Commit
on:
  push:
    branches: [ feature/post ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Setar a branch
      run: git checkout feature/post

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Executar rota
      run: npm run dev