name: CI - Pull Request
on:
  pull_request:
    branches: - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependÃªncias
        run: npm install

      - name: Executar rota
        run: npm run dev